default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
      - id: check-ast
      - id: end-of-file-fixer
      - id: check-yaml
        args: [ --unsafe ]
      - id: check-toml
      - id: check-merge-conflict
      - id: check-added-large-files
        args: [ --maxkb=1000 ]
      - id: debug-statements
      - id: detect-private-key
      - id: mixed-line-ending
        args: [ --fix=lf ]

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.10
    hooks:
      - id: ruff-check
        args: [ --fix ]
        files: ^src/
      - id: ruff-format
        files: ^src/

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        files: ^src/
        additional_dependencies:
          - pydantic>=2.11.7
